algoritmo "Algoritmo_Exercicio3"
// Disciplina  :  [Linguagem e Lógica de Programação] 
// Professor   : Antonio Carlos Nicolodi 
// Função : Cálculo do valor do ingresso e quantidade de pessoas
// Autor : Gabriel Wojcik
// Data : 16/03/2020
// Seção de Declarações 
var
   quantidade : inteiro
   total : real
   
   


inicio
// Seção de Comandos
   leia(quantidade)
   escreva(quantidade)
   total <- 320 * quantidade
   escreva (total)

 
fimalgoritmo
