algoritmo "Algoritmo_Maior_QueOSegundo"
// Função : Algoritmo que lê dois números e apresenta o MAIOR
// Autor : Gabriel Wojcik
// Data : 16/03/2020
// Seção de Declarações 
var
   num1 : inteiro
   num2 : inteiro

inicio
// Seção de Comandos 
    Escreva("Informe o primeiro número: ")
    leia(num1)
    escreva("Informe o primeiro número: ")
    leia(num2)
    se (num1 > num2) entao
       escreva(" O primeiro é maior que o segundo")
    fimse


fimalgoritmo
