Algoritmo "semnome"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 14/05/2020
Var
produtos : caractere
resp     : caractere
preco    : real


Inicio
escreval("Oque voce comprou")
leia(produtos)
se(resposta="fruta")ENTAO
escreval(produtos)
Fimse



Fimalgoritmo